name: Categorize Articles with AI

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  categorize:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AI Categorization
        run: |
          curl -X GET https://windfarm-zeta.vercel.app/api/refresh \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -w "\nHTTP Status: %{http_code}\n"
